package score

import (
	"bufio"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// generatedDetector checks whether files are generated code that should be
// excluded from scoring. Checks three sources in order:
// 1. .gitattributes linguist-generated markers
// 2. Header comments (first 5 lines) matching known generator patterns
// 3. Filename conventions (*_generated.go, *.pb.go, migrations/, etc.)
type generatedDetector struct {
	patterns    map[string]bool // glob patterns from .gitattributes linguist-generated
	checkedDirs map[string]bool // directories already scanned for .gitattributes
}

func newGeneratedDetector(projectFiles map[string]bool) *generatedDetector {
	d := &generatedDetector{
		patterns:    make(map[string]bool),
		checkedDirs: make(map[string]bool),
	}

	// Find and parse .gitattributes
	for path := range projectFiles {
		dir := filepath.Dir(path)
		for dir != "." && dir != "/" {
			if d.checkedDirs[dir] {
				break
			}
			d.checkedDirs[dir] = true
			gaPath := filepath.Join(dir, ".gitattributes")
			d.loadGitattributes(gaPath)
			dir = filepath.Dir(dir)
		}
	}

	return d
}

func (d *generatedDetector) loadGitattributes(path string) {
	f, err := os.Open(path) //nolint:gosec
	if err != nil {
		return
	}
	defer f.Close() //nolint:errcheck

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.Contains(line, "linguist-generated") {
			// Extract the pattern (first field)
			fields := strings.Fields(line)
			if len(fields) >= 1 {
				d.patterns[fields[0]] = true
			}
		}
	}
}

// IsGenerated returns true if the file should be treated as generated code.
func (d *generatedDetector) IsGenerated(path string, firstLines []string) bool {
	// 1. Check .gitattributes patterns
	base := filepath.Base(path)
	relPath := path
	for pattern := range d.patterns {
		if matched, _ := filepath.Match(pattern, base); matched {
			return true
		}
		if matched, _ := filepath.Match(pattern, relPath); matched {
			return true
		}
	}

	// 2. Check header comments for generator markers
	for _, line := range firstLines {
		lower := strings.ToLower(line)
		if containsGeneratorMarker(lower) {
			return true
		}
	}

	// 3. Check filename conventions
	if isGeneratedFilename(path) {
		return true
	}

	return false
}

var generatorMarkers = []string{
	"do not edit",
	"don't edit",
	"auto-generated",
	"autogenerated",
	"automatically generated",
	"code generated by",
	"generated by ",
	"@generated",
	"this file is generated",
	"machine generated",
}

func containsGeneratorMarker(line string) bool {
	for _, marker := range generatorMarkers {
		if strings.Contains(line, marker) {
			return true
		}
	}
	return false
}

var generatedPatterns = []string{
	"*_generated.go",
	"*_generated.py",
	"*_generated.ts",
	"*.gen.go",
	"*.gen.ts",
	"*.pb.go",  // protobuf
	"*_pb2.py", // protobuf python
	"*_pb2_grpc.py",
	"*.min.js",
	"*.min.css",
	"*.bundle.js",
	"*.bundle.ts",
}

var generatedDirs = []string{
	"migrations",
	"generated",
}

func isGeneratedFilename(path string) bool {
	base := filepath.Base(path)

	for _, pattern := range generatedPatterns {
		if matched, _ := filepath.Match(pattern, base); matched {
			return true
		}
	}

	// Check if any path component is a generated directory
	parts := strings.SplitSeq(filepath.ToSlash(path), "/")
	for part := range parts {
		if slices.Contains(generatedDirs, part) {
			return true
		}
	}

	return false
}
